/**
 * Amphora Data Api
 * API for interacting with the Amphora Data platform.
 *
 * The version of the OpenAPI document: 0.9.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Amphoradata);
  }
}(this, function(expect, Amphoradata) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Amphoradata.Address();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Address', function() {
    it('should create an instance of Address', function() {
      // uncomment below and update the code to test Address
      //var instane = new Amphoradata.Address();
      //expect(instance).to.be.a(Amphoradata.Address);
    });

    it('should have the property streetNumber (base name: "streetNumber")', function() {
      // uncomment below and update the code to test the property streetNumber
      //var instane = new Amphoradata.Address();
      //expect(instance).to.be();
    });

    it('should have the property streetName (base name: "streetName")', function() {
      // uncomment below and update the code to test the property streetName
      //var instane = new Amphoradata.Address();
      //expect(instance).to.be();
    });

    it('should have the property municipalitySubdivision (base name: "municipalitySubdivision")', function() {
      // uncomment below and update the code to test the property municipalitySubdivision
      //var instane = new Amphoradata.Address();
      //expect(instance).to.be();
    });

    it('should have the property municipality (base name: "municipality")', function() {
      // uncomment below and update the code to test the property municipality
      //var instane = new Amphoradata.Address();
      //expect(instance).to.be();
    });

    it('should have the property countrySecondarySubdivision (base name: "countrySecondarySubdivision")', function() {
      // uncomment below and update the code to test the property countrySecondarySubdivision
      //var instane = new Amphoradata.Address();
      //expect(instance).to.be();
    });

    it('should have the property countrySubdivision (base name: "countrySubdivision")', function() {
      // uncomment below and update the code to test the property countrySubdivision
      //var instane = new Amphoradata.Address();
      //expect(instance).to.be();
    });

    it('should have the property postalCode (base name: "postalCode")', function() {
      // uncomment below and update the code to test the property postalCode
      //var instane = new Amphoradata.Address();
      //expect(instance).to.be();
    });

    it('should have the property countryCode (base name: "countryCode")', function() {
      // uncomment below and update the code to test the property countryCode
      //var instane = new Amphoradata.Address();
      //expect(instance).to.be();
    });

    it('should have the property country (base name: "country")', function() {
      // uncomment below and update the code to test the property country
      //var instane = new Amphoradata.Address();
      //expect(instance).to.be();
    });

    it('should have the property countryCodeIso3 (base name: "countryCodeIso3")', function() {
      // uncomment below and update the code to test the property countryCodeIso3
      //var instane = new Amphoradata.Address();
      //expect(instance).to.be();
    });

    it('should have the property freeformAddress (base name: "freeformAddress")', function() {
      // uncomment below and update the code to test the property freeformAddress
      //var instane = new Amphoradata.Address();
      //expect(instance).to.be();
    });

    it('should have the property localName (base name: "localName")', function() {
      // uncomment below and update the code to test the property localName
      //var instane = new Amphoradata.Address();
      //expect(instance).to.be();
    });

  });

}));
