/**
 * Amphora Data Api
 * API for interacting with the Amphora Data platform.
 *
 * The version of the OpenAPI document: 0.9.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Amphoradata);
  }
}(this, function(expect, Amphoradata) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Amphoradata.DetailedAmphora();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DetailedAmphora', function() {
    it('should create an instance of DetailedAmphora', function() {
      // uncomment below and update the code to test DetailedAmphora
      //var instane = new Amphoradata.DetailedAmphora();
      //expect(instance).to.be.a(Amphoradata.DetailedAmphora);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new Amphoradata.DetailedAmphora();
      //expect(instance).to.be();
    });

    it('should have the property isDeleted (base name: "isDeleted")', function() {
      // uncomment below and update the code to test the property isDeleted
      //var instane = new Amphoradata.DetailedAmphora();
      //expect(instance).to.be();
    });

    it('should have the property createdDate (base name: "createdDate")', function() {
      // uncomment below and update the code to test the property createdDate
      //var instane = new Amphoradata.DetailedAmphora();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new Amphoradata.DetailedAmphora();
      //expect(instance).to.be();
    });

    it('should have the property price (base name: "price")', function() {
      // uncomment below and update the code to test the property price
      //var instane = new Amphoradata.DetailedAmphora();
      //expect(instance).to.be();
    });

    it('should have the property labels (base name: "labels")', function() {
      // uncomment below and update the code to test the property labels
      //var instane = new Amphoradata.DetailedAmphora();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instane = new Amphoradata.DetailedAmphora();
      //expect(instance).to.be();
    });

    it('should have the property lat (base name: "lat")', function() {
      // uncomment below and update the code to test the property lat
      //var instane = new Amphoradata.DetailedAmphora();
      //expect(instance).to.be();
    });

    it('should have the property lon (base name: "lon")', function() {
      // uncomment below and update the code to test the property lon
      //var instane = new Amphoradata.DetailedAmphora();
      //expect(instance).to.be();
    });

    it('should have the property termsAndConditionsId (base name: "termsAndConditionsId")', function() {
      // uncomment below and update the code to test the property termsAndConditionsId
      //var instane = new Amphoradata.DetailedAmphora();
      //expect(instance).to.be();
    });

    it('should have the property fileAttributes (base name: "fileAttributes")', function() {
      // uncomment below and update the code to test the property fileAttributes
      //var instane = new Amphoradata.DetailedAmphora();
      //expect(instance).to.be();
    });

    it('should have the property organisationId (base name: "organisationId")', function() {
      // uncomment below and update the code to test the property organisationId
      //var instane = new Amphoradata.DetailedAmphora();
      //expect(instance).to.be();
    });

    it('should have the property purchaseCount (base name: "purchaseCount")', function() {
      // uncomment below and update the code to test the property purchaseCount
      //var instane = new Amphoradata.DetailedAmphora();
      //expect(instance).to.be();
    });

  });

}));
