/**
 * Amphora Data Api
 * API for interacting with the Amphora Data platform.
 *
 * The version of the OpenAPI document: 0.9.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Amphoradata);
  }
}(this, function(expect, Amphoradata) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Amphoradata.GetSeries();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('GetSeries', function() {
    it('should create an instance of GetSeries', function() {
      // uncomment below and update the code to test GetSeries
      //var instane = new Amphoradata.GetSeries();
      //expect(instance).to.be.a(Amphoradata.GetSeries);
    });

    it('should have the property timeSeriesId (base name: "timeSeriesId")', function() {
      // uncomment below and update the code to test the property timeSeriesId
      //var instane = new Amphoradata.GetSeries();
      //expect(instance).to.be();
    });

    it('should have the property searchSpan (base name: "searchSpan")', function() {
      // uncomment below and update the code to test the property searchSpan
      //var instane = new Amphoradata.GetSeries();
      //expect(instance).to.be();
    });

    it('should have the property filter (base name: "filter")', function() {
      // uncomment below and update the code to test the property filter
      //var instane = new Amphoradata.GetSeries();
      //expect(instance).to.be();
    });

    it('should have the property projectedVariables (base name: "projectedVariables")', function() {
      // uncomment below and update the code to test the property projectedVariables
      //var instane = new Amphoradata.GetSeries();
      //expect(instance).to.be();
    });

    it('should have the property inlineVariables (base name: "inlineVariables")', function() {
      // uncomment below and update the code to test the property inlineVariables
      //var instane = new Amphoradata.GetSeries();
      //expect(instance).to.be();
    });

  });

}));
