/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import { ServiceClient, ServiceClientOptions } from 'ms-rest';
import * as models from "./models";
import * as operations from "./operations";

export default class Client extends ServiceClient {
  /**
   * @class
   * Initializes a new instance of the Client class.
   * @constructor
   *
   * @param {string} [baseUri] - The base URI of the service.
   *
   * @param {object} [options] - The parameter options
   *
   * @param {Array} [options.filters] - Filters to be added to the request pipeline
   *
   * @param {object} [options.requestOptions] - Options for the underlying request object
   * {@link https://github.com/request/request#requestoptions-callback Options doc}
   *
   * @param {boolean} [options.noRetryPolicy] - If set to true, turn off default retry policy
   *
   */
  constructor(baseUri?: string, options?: ServiceClientOptions);

  // Operation groups
  authentication: operations.Authentication;
  market: operations.Market;
  organisationRestriction: operations.OrganisationRestriction;
  organisations: operations.Organisations;
  search: operations.Search;
  users: operations.Users;
  version: operations.Version;
  accountOperations: operations.AccountOperations;
  termsAndConditionsOperations: operations.TermsAndConditionsOperations;
  amphorae: operations.Amphorae;
  amphoraeFiles: operations.AmphoraeFiles;
  amphoraeSignals: operations.AmphoraeSignals;
  purchases: operations.Purchases;
  timeSeries: operations.TimeSeries;
}

export { Client, models as Models };
