## AutoRest configuration ... @microsoft.azure/autorest-core@3.0.5537

override-client-name: Client
nodejs: 
  - output-folder: src
    package-name: amphoradata
use:
  - "@microsoft.azure/autorest.nodejs@2.1.128"
directive:
  - from: swagger-document
    where: $..*[?(@.additionalProperties == false)]
    transform: $.additionalProperties = undefined;