version: "3"
services:
  generator:
    image: openapitools/openapi-generator-cli:v4.2.0
    volumes: 
      - ${PWD}/src:/local
    command: generate -i https://app.amphoradata.com/swagger/v1/swagger.json -g typescript-axios -o /local/sdk --skip-validate-spec --enable-post-process-file