/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a AggregateVariable.
 */
class AggregateVariable {
  /**
   * Create a AggregateVariable.
   * @property {object} [filter]
   * @property {object} [aggregation]
   * @property {string} kind Polymorphic Discriminator
   */
  constructor() {
  }

  /**
   * Defines the metadata of AggregateVariable
   *
   * @returns {object} metadata of AggregateVariable
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'AggregateVariable',
      type: {
        name: 'Composite',
        polymorphicDiscriminator: {
          serializedName: 'kind',
          clientName: 'kind'
        },
        uberParent: 'AggregateVariable',
        className: 'AggregateVariable',
        modelProperties: {
          filter: {
            required: false,
            serializedName: 'filter',
            type: {
              name: 'Object'
            }
          },
          aggregation: {
            required: false,
            serializedName: 'aggregation',
            type: {
              name: 'Object'
            }
          },
          kind: {
            required: true,
            serializedName: 'kind',
            isPolymorphicDiscriminator: true,
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = AggregateVariable;
