/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a AggregateSeries.
 */
class AggregateSeries {
  /**
   * Create a AggregateSeries.
   * @property {array} [timeSeriesId]
   * @property {object} [searchSpan]
   * @property {object} [filter]
   * @property {string} [interval]
   * @property {array} [projectedVariables]
   * @property {object} [inlineVariables]
   */
  constructor() {
  }

  /**
   * Defines the metadata of AggregateSeries
   *
   * @returns {object} metadata of AggregateSeries
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'AggregateSeries',
      type: {
        name: 'Composite',
        className: 'AggregateSeries',
        modelProperties: {
          timeSeriesId: {
            required: false,
            serializedName: 'timeSeriesId',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'ObjectElementType',
                  type: {
                    name: 'Object'
                  }
              }
            }
          },
          searchSpan: {
            required: false,
            serializedName: 'searchSpan',
            type: {
              name: 'Object'
            }
          },
          filter: {
            required: false,
            serializedName: 'filter',
            type: {
              name: 'Object'
            }
          },
          interval: {
            required: false,
            serializedName: 'interval',
            type: {
              name: 'String'
            }
          },
          projectedVariables: {
            required: false,
            serializedName: 'projectedVariables',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'StringElementType',
                  type: {
                    name: 'String'
                  }
              }
            }
          },
          inlineVariables: {
            required: false,
            serializedName: 'inlineVariables',
            type: {
              name: 'Dictionary',
              value: {
                  required: false,
                  serializedName: 'VariableElementType',
                  type: {
                    name: 'Composite',
                    polymorphicDiscriminator: {
                      serializedName: 'kind',
                      clientName: 'kind'
                    },
                    uberParent: 'Variable',
                    className: 'Variable'
                  }
              }
            }
          }
        }
      }
    };
  }
}

module.exports = AggregateSeries;
