/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a AmphoraUser.
 */
class AmphoraUser {
  /**
   * Create a AmphoraUser.
   * @property {string} [id]
   * @property {string} [email]
   * @property {string} [about]
   * @property {string} [fullName]
   * @property {string} [organisationId]
   * @property {string} [userName]
   * @property {date} [lastModified]
   */
  constructor() {
  }

  /**
   * Defines the metadata of AmphoraUser
   *
   * @returns {object} metadata of AmphoraUser
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'AmphoraUser',
      type: {
        name: 'Composite',
        className: 'AmphoraUser',
        modelProperties: {
          id: {
            required: false,
            serializedName: 'id',
            type: {
              name: 'String'
            }
          },
          email: {
            required: false,
            serializedName: 'email',
            type: {
              name: 'String'
            }
          },
          about: {
            required: false,
            serializedName: 'about',
            type: {
              name: 'String'
            }
          },
          fullName: {
            required: false,
            serializedName: 'fullName',
            type: {
              name: 'String'
            }
          },
          organisationId: {
            required: false,
            serializedName: 'organisationId',
            type: {
              name: 'String'
            }
          },
          userName: {
            required: false,
            serializedName: 'userName',
            type: {
              name: 'String'
            }
          },
          lastModified: {
            required: false,
            serializedName: 'lastModified',
            type: {
              name: 'DateTime'
            }
          }
        }
      }
    };
  }
}

module.exports = AmphoraUser;
