/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a BasicAmphora.
 */
class BasicAmphora {
  /**
   * Create a BasicAmphora.
   * @property {string} [id]
   * @property {boolean} [isDeleted]
   * @property {date} [createdDate]
   * @property {string} name
   * @property {number} price
   * @property {string} [labels]
   */
  constructor() {
  }

  /**
   * Defines the metadata of BasicAmphora
   *
   * @returns {object} metadata of BasicAmphora
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'BasicAmphora',
      type: {
        name: 'Composite',
        className: 'BasicAmphora',
        modelProperties: {
          id: {
            required: false,
            serializedName: 'id',
            type: {
              name: 'String'
            }
          },
          isDeleted: {
            required: false,
            nullable: true,
            serializedName: 'isDeleted',
            type: {
              name: 'Boolean'
            }
          },
          createdDate: {
            required: false,
            serializedName: 'createdDate',
            type: {
              name: 'DateTime'
            }
          },
          name: {
            required: true,
            serializedName: 'name',
            type: {
              name: 'String'
            }
          },
          price: {
            required: true,
            serializedName: 'price',
            type: {
              name: 'Number'
            }
          },
          labels: {
            required: false,
            serializedName: 'labels',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = BasicAmphora;
