/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a CategorySet.
 */
class CategorySet {
  /**
   * Create a CategorySet.
   * @property {number} [id]
   */
  constructor() {
  }

  /**
   * Defines the metadata of CategorySet
   *
   * @returns {object} metadata of CategorySet
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'CategorySet',
      type: {
        name: 'Composite',
        className: 'CategorySet',
        modelProperties: {
          id: {
            required: false,
            serializedName: 'id',
            type: {
              name: 'Number'
            }
          }
        }
      }
    };
  }
}

module.exports = CategorySet;
