/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a Componentsschemasbasicamphoraallof1.
 */
class Componentsschemasbasicamphoraallof1 {
  /**
   * Create a Componentsschemasbasicamphoraallof1.
   * @property {string} name
   * @property {number} price
   * @property {string} [labels]
   */
  constructor() {
  }

  /**
   * Defines the metadata of Componentsschemasbasicamphoraallof1
   *
   * @returns {object} metadata of Componentsschemasbasicamphoraallof1
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'components·schemas·basicamphora·allof·1',
      type: {
        name: 'Composite',
        className: 'Componentsschemasbasicamphoraallof1',
        modelProperties: {
          name: {
            required: true,
            serializedName: 'name',
            type: {
              name: 'String'
            }
          },
          price: {
            required: true,
            serializedName: 'price',
            type: {
              name: 'Number'
            }
          },
          labels: {
            required: false,
            serializedName: 'labels',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = Componentsschemasbasicamphoraallof1;
