/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a Componentsschemaspropertyvaluesallof1.
 */
class Componentsschemaspropertyvaluesallof1 {
  /**
   * Create a Componentsschemaspropertyvaluesallof1.
   * @property {array} [values]
   */
  constructor() {
  }

  /**
   * Defines the metadata of Componentsschemaspropertyvaluesallof1
   *
   * @returns {object} metadata of Componentsschemaspropertyvaluesallof1
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'components·schemas·propertyvalues·allof·1',
      type: {
        name: 'Composite',
        className: 'Componentsschemaspropertyvaluesallof1',
        modelProperties: {
          values: {
            required: false,
            serializedName: 'values',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'ObjectElementType',
                  type: {
                    name: 'Object'
                  }
              }
            }
          }
        }
      }
    };
  }
}

module.exports = Componentsschemaspropertyvaluesallof1;
