/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a Componentsschemascreateamphoraallof1.
 */
class Componentsschemascreateamphoraallof1 {
  /**
   * Create a Componentsschemascreateamphoraallof1.
   * @property {string} description
   * @property {number} [lat] Latitude.
   * @property {number} [lon] Longitude.
   * @property {string} [termsAndConditionsId]
   */
  constructor() {
  }

  /**
   * Defines the metadata of Componentsschemascreateamphoraallof1
   *
   * @returns {object} metadata of Componentsschemascreateamphoraallof1
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'components·schemas·createamphora·allof·1',
      type: {
        name: 'Composite',
        className: 'Componentsschemascreateamphoraallof1',
        modelProperties: {
          description: {
            required: true,
            serializedName: 'description',
            type: {
              name: 'String'
            }
          },
          lat: {
            required: false,
            nullable: true,
            serializedName: 'lat',
            type: {
              name: 'Number'
            }
          },
          lon: {
            required: false,
            nullable: true,
            serializedName: 'lon',
            type: {
              name: 'Number'
            }
          },
          termsAndConditionsId: {
            required: false,
            serializedName: 'termsAndConditionsId',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = Componentsschemascreateamphoraallof1;
