/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a CreateAmphora.
 */
class CreateAmphora {
  /**
   * Create a CreateAmphora.
   * @property {string} [id]
   * @property {boolean} [isDeleted]
   * @property {date} [createdDate]
   * @property {string} name
   * @property {number} price
   * @property {string} [labels]
   * @property {string} description
   * @property {number} [lat] Latitude.
   * @property {number} [lon] Longitude.
   * @property {string} [termsAndConditionsId]
   */
  constructor() {
  }

  /**
   * Defines the metadata of CreateAmphora
   *
   * @returns {object} metadata of CreateAmphora
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'CreateAmphora',
      type: {
        name: 'Composite',
        className: 'CreateAmphora',
        modelProperties: {
          id: {
            required: false,
            serializedName: 'id',
            type: {
              name: 'String'
            }
          },
          isDeleted: {
            required: false,
            nullable: true,
            serializedName: 'isDeleted',
            type: {
              name: 'Boolean'
            }
          },
          createdDate: {
            required: false,
            serializedName: 'createdDate',
            type: {
              name: 'DateTime'
            }
          },
          name: {
            required: true,
            serializedName: 'name',
            type: {
              name: 'String'
            }
          },
          price: {
            required: true,
            serializedName: 'price',
            type: {
              name: 'Number'
            }
          },
          labels: {
            required: false,
            serializedName: 'labels',
            type: {
              name: 'String'
            }
          },
          description: {
            required: true,
            serializedName: 'description',
            type: {
              name: 'String'
            }
          },
          lat: {
            required: false,
            nullable: true,
            serializedName: 'lat',
            type: {
              name: 'Number'
            }
          },
          lon: {
            required: false,
            nullable: true,
            serializedName: 'lon',
            type: {
              name: 'Number'
            }
          },
          termsAndConditionsId: {
            required: false,
            serializedName: 'termsAndConditionsId',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = CreateAmphora;
