/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a DateTimeRange.
 */
class DateTimeRange {
  /**
   * Create a DateTimeRange.
   * @property {date} [from]
   * @property {date} [to]
   */
  constructor() {
  }

  /**
   * Defines the metadata of DateTimeRange
   *
   * @returns {object} metadata of DateTimeRange
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'DateTimeRange',
      type: {
        name: 'Composite',
        className: 'DateTimeRange',
        modelProperties: {
          from: {
            required: false,
            serializedName: 'from',
            type: {
              name: 'DateTime'
            }
          },
          to: {
            required: false,
            serializedName: 'to',
            type: {
              name: 'DateTime'
            }
          }
        }
      }
    };
  }
}

module.exports = DateTimeRange;
