/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a EditAmphora.
 */
class EditAmphora {
  /**
   * Create a EditAmphora.
   * @property {string} [id]
   * @property {boolean} [isDeleted]
   * @property {date} [createdDate]
   * @property {string} name
   * @property {number} price
   * @property {string} [labels]
   * @property {string} description
   * @property {number} [lat] Latitude.
   * @property {number} [lon] Longitude.
   * @property {string} [termsAndConditionsId]
   * @property {object} [fileAttributes]
   */
  constructor() {
  }

  /**
   * Defines the metadata of EditAmphora
   *
   * @returns {object} metadata of EditAmphora
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'EditAmphora',
      type: {
        name: 'Composite',
        className: 'EditAmphora',
        modelProperties: {
          id: {
            required: false,
            serializedName: 'id',
            type: {
              name: 'String'
            }
          },
          isDeleted: {
            required: false,
            nullable: true,
            serializedName: 'isDeleted',
            type: {
              name: 'Boolean'
            }
          },
          createdDate: {
            required: false,
            serializedName: 'createdDate',
            type: {
              name: 'DateTime'
            }
          },
          name: {
            required: true,
            serializedName: 'name',
            type: {
              name: 'String'
            }
          },
          price: {
            required: true,
            serializedName: 'price',
            type: {
              name: 'Number'
            }
          },
          labels: {
            required: false,
            serializedName: 'labels',
            type: {
              name: 'String'
            }
          },
          description: {
            required: true,
            serializedName: 'description',
            type: {
              name: 'String'
            }
          },
          lat: {
            required: false,
            nullable: true,
            serializedName: 'lat',
            type: {
              name: 'Number'
            }
          },
          lon: {
            required: false,
            nullable: true,
            serializedName: 'lon',
            type: {
              name: 'Number'
            }
          },
          termsAndConditionsId: {
            required: false,
            serializedName: 'termsAndConditionsId',
            type: {
              name: 'String'
            }
          },
          fileAttributes: {
            required: false,
            serializedName: 'fileAttributes',
            type: {
              name: 'Dictionary',
              value: {
                  required: false,
                  serializedName: 'AttributeStoreElementType',
                  type: {
                    name: 'Composite',
                    className: 'AttributeStore'
                  }
              }
            }
          }
        }
      }
    };
  }
}

module.exports = EditAmphora;
