/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a Entity.
 */
class Entity {
  /**
   * Create a Entity.
   * @property {string} [id]
   * @property {boolean} [isDeleted]
   * @property {date} [createdDate]
   */
  constructor() {
  }

  /**
   * Defines the metadata of Entity
   *
   * @returns {object} metadata of Entity
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'Entity',
      type: {
        name: 'Composite',
        className: 'Entity',
        modelProperties: {
          id: {
            required: false,
            serializedName: 'id',
            type: {
              name: 'String'
            }
          },
          isDeleted: {
            required: false,
            nullable: true,
            serializedName: 'isDeleted',
            type: {
              name: 'Boolean'
            }
          },
          createdDate: {
            required: false,
            serializedName: 'createdDate',
            type: {
              name: 'DateTime'
            }
          }
        }
      }
    };
  }
}

module.exports = Entity;
