/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a EntryPoint.
 */
class EntryPoint {
  /**
   * Create a EntryPoint.
   * @property {string} [type]
   * @property {object} [position]
   */
  constructor() {
  }

  /**
   * Defines the metadata of EntryPoint
   *
   * @returns {object} metadata of EntryPoint
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'EntryPoint',
      type: {
        name: 'Composite',
        className: 'EntryPoint',
        modelProperties: {
          type: {
            required: false,
            serializedName: 'type',
            type: {
              name: 'String'
            }
          },
          position: {
            required: false,
            serializedName: 'position',
            type: {
              name: 'Object'
            }
          }
        }
      }
    };
  }
}

module.exports = EntryPoint;
