/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a EventProperty.
 */
class EventProperty {
  /**
   * Create a EventProperty.
   * @property {string} [name]
   * @property {string} [type]
   */
  constructor() {
  }

  /**
   * Defines the metadata of EventProperty
   *
   * @returns {object} metadata of EventProperty
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'EventProperty',
      type: {
        name: 'Composite',
        className: 'EventProperty',
        modelProperties: {
          name: {
            required: false,
            serializedName: 'name',
            type: {
              name: 'String'
            }
          },
          type: {
            required: false,
            serializedName: 'type',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = EventProperty;
