/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a FuzzySearchResponse.
 */
class FuzzySearchResponse {
  /**
   * Create a FuzzySearchResponse.
   * @property {object} [summary]
   * @property {array} [results]
   */
  constructor() {
  }

  /**
   * Defines the metadata of FuzzySearchResponse
   *
   * @returns {object} metadata of FuzzySearchResponse
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'FuzzySearchResponse',
      type: {
        name: 'Composite',
        className: 'FuzzySearchResponse',
        modelProperties: {
          summary: {
            required: false,
            serializedName: 'summary',
            type: {
              name: 'Object'
            }
          },
          results: {
            required: false,
            serializedName: 'results',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'ResultElementType',
                  type: {
                    name: 'Composite',
                    className: 'Result'
                  }
              }
            }
          }
        }
      }
    };
  }
}

module.exports = FuzzySearchResponse;
