/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a GenericResponse.
 */
class GenericResponse {
  /**
   * Create a GenericResponse.
   * @property {string} [message]
   */
  constructor() {
  }

  /**
   * Defines the metadata of GenericResponse
   *
   * @returns {object} metadata of GenericResponse
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'GenericResponse',
      type: {
        name: 'Composite',
        className: 'GenericResponse',
        modelProperties: {
          message: {
            required: false,
            serializedName: 'message',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = GenericResponse;
