/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

/* jshint latedef:false */
/* jshint forin:false */
/* jshint noempty:false */

'use strict';

exports.BasicAmphora = require('./basicAmphora');
exports.TermsAndConditions = require('./termsAndConditions');
exports.Signal = require('./signal');
exports.TokenRequest = require('./tokenRequest');
exports.EntryPoint = require('./entryPoint');
exports.Result = require('./result');
exports.FuzzySearchResponse = require('./fuzzySearchResponse');
exports.Summary = require('./summary');
exports.Address = require('./address');
exports.Position = require('./position');
exports.Viewport = require('./viewport');
exports.CategorySet = require('./categorySet');
exports.Name = require('./name');
exports.Classification = require('./classification');
exports.Poi = require('./poi');
exports.Componentsschemasbasicamphoraallof1 = require('./componentsschemasbasicamphoraallof1');
exports.Entity = require('./entity');
exports.Restriction = require('./restriction');
exports.GenericResponse = require('./genericResponse');
exports.Organisation = require('./organisation');
exports.Componentsschemasorganisationallof1 = require('./componentsschemasorganisationallof1');
exports.AmphoraUser = require('./amphoraUser');
exports.Account = require('./account');
exports.ProblemDetails = require('./problemDetails');
exports.AttributeStore = require('./attributeStore');
exports.DetailedAmphora = require('./detailedAmphora');
exports.Componentsschemasdetailedamphoraallof1 = require('./componentsschemasdetailedamphoraallof1');
exports.EditAmphora = require('./editAmphora');
exports.Componentsschemaseditamphoraallof1 = require('./componentsschemaseditamphoraallof1');
exports.CreateAmphora = require('./createAmphora');
exports.Componentsschemascreateamphoraallof1 = require('./componentsschemascreateamphoraallof1');
exports.UploadResponse = require('./uploadResponse');
exports.UpdateSignal = require('./updateSignal');
exports.PropertyValues = require('./propertyValues');
exports.QueryResultPage = require('./queryResultPage');
exports.Componentsschemasqueryresultpageallof1 = require('./componentsschemasqueryresultpageallof1');
exports.Componentsschemaspropertyvaluesallof1 = require('./componentsschemaspropertyvaluesallof1');
exports.EventProperty = require('./eventProperty');
exports.PagedResponse = require('./pagedResponse');
exports.QueryRequest = require('./queryRequest');
exports.GetEvents = require('./getEvents');
exports.DateTimeRange = require('./dateTimeRange');
exports.Tsx = require('./tsx');
exports.Variable = require('./variable');
exports.GetSeries = require('./getSeries');
exports.NumericVariable = require('./numericVariable');
exports.AggregateVariable = require('./aggregateVariable');
exports.AggregateSeries = require('./aggregateSeries');
exports.discriminators = {
  'Variable' : exports.Variable,
  'NumericVariable' : exports.NumericVariable,
  'AggregateVariable' : exports.AggregateVariable
};
