/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a Name.
 */
class Name {
  /**
   * Create a Name.
   * @property {string} [nameLocale]
   * @property {string} [nameName]
   */
  constructor() {
  }

  /**
   * Defines the metadata of Name
   *
   * @returns {object} metadata of Name
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'Name',
      type: {
        name: 'Composite',
        className: 'Name',
        modelProperties: {
          nameLocale: {
            required: false,
            serializedName: 'nameLocale',
            type: {
              name: 'String'
            }
          },
          nameName: {
            required: false,
            serializedName: 'nameName',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = Name;
