/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a Organisation.
 */
class Organisation {
  /**
   * Create a Organisation.
   * @property {string} [id]
   * @property {boolean} [isDeleted]
   * @property {date} [createdDate]
   * @property {string} [name]
   * @property {string} [about]
   * @property {string} [websiteUrl]
   * @property {string} [address]
   */
  constructor() {
  }

  /**
   * Defines the metadata of Organisation
   *
   * @returns {object} metadata of Organisation
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'Organisation',
      type: {
        name: 'Composite',
        className: 'Organisation',
        modelProperties: {
          id: {
            required: false,
            serializedName: 'id',
            type: {
              name: 'String'
            }
          },
          isDeleted: {
            required: false,
            nullable: true,
            serializedName: 'isDeleted',
            type: {
              name: 'Boolean'
            }
          },
          createdDate: {
            required: false,
            serializedName: 'createdDate',
            type: {
              name: 'DateTime'
            }
          },
          name: {
            required: false,
            serializedName: 'name',
            type: {
              name: 'String'
            }
          },
          about: {
            required: false,
            serializedName: 'about',
            type: {
              name: 'String'
            }
          },
          websiteUrl: {
            required: false,
            serializedName: 'websiteUrl',
            type: {
              name: 'String'
            }
          },
          address: {
            required: false,
            serializedName: 'address',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = Organisation;
