/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a PagedResponse.
 */
class PagedResponse {
  /**
   * Create a PagedResponse.
   * @property {string} [continuationToken]
   */
  constructor() {
  }

  /**
   * Defines the metadata of PagedResponse
   *
   * @returns {object} metadata of PagedResponse
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'PagedResponse',
      type: {
        name: 'Composite',
        className: 'PagedResponse',
        modelProperties: {
          continuationToken: {
            required: false,
            serializedName: 'continuationToken',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = PagedResponse;
