/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a Poi.
 */
class Poi {
  /**
   * Create a Poi.
   * @property {string} [name]
   * @property {string} [phone]
   * @property {array} [categorySet]
   * @property {array} [categories]
   * @property {array} [classifications]
   */
  constructor() {
  }

  /**
   * Defines the metadata of Poi
   *
   * @returns {object} metadata of Poi
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'Poi',
      type: {
        name: 'Composite',
        className: 'Poi',
        modelProperties: {
          name: {
            required: false,
            serializedName: 'name',
            type: {
              name: 'String'
            }
          },
          phone: {
            required: false,
            serializedName: 'phone',
            type: {
              name: 'String'
            }
          },
          categorySet: {
            required: false,
            serializedName: 'categorySet',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'CategorySetElementType',
                  type: {
                    name: 'Composite',
                    className: 'CategorySet'
                  }
              }
            }
          },
          categories: {
            required: false,
            serializedName: 'categories',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'StringElementType',
                  type: {
                    name: 'String'
                  }
              }
            }
          },
          classifications: {
            required: false,
            serializedName: 'classifications',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'ClassificationElementType',
                  type: {
                    name: 'Composite',
                    className: 'Classification'
                  }
              }
            }
          }
        }
      }
    };
  }
}

module.exports = Poi;
