/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a PropertyValues.
 */
class PropertyValues {
  /**
   * Create a PropertyValues.
   * @property {string} [name]
   * @property {string} [type]
   * @property {array} [values]
   */
  constructor() {
  }

  /**
   * Defines the metadata of PropertyValues
   *
   * @returns {object} metadata of PropertyValues
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'PropertyValues',
      type: {
        name: 'Composite',
        className: 'PropertyValues',
        modelProperties: {
          name: {
            required: false,
            serializedName: 'name',
            type: {
              name: 'String'
            }
          },
          type: {
            required: false,
            serializedName: 'type',
            type: {
              name: 'String'
            }
          },
          values: {
            required: false,
            serializedName: 'values',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'ObjectElementType',
                  type: {
                    name: 'Object'
                  }
              }
            }
          }
        }
      }
    };
  }
}

module.exports = PropertyValues;
