/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a QueryRequest.
 */
class QueryRequest {
  /**
   * Create a QueryRequest.
   * @property {object} [getEvents]
   * @property {object} [getSeries]
   * @property {object} [aggregateSeries]
   */
  constructor() {
  }

  /**
   * Defines the metadata of QueryRequest
   *
   * @returns {object} metadata of QueryRequest
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'QueryRequest',
      type: {
        name: 'Composite',
        className: 'QueryRequest',
        modelProperties: {
          getEvents: {
            required: false,
            serializedName: 'getEvents',
            type: {
              name: 'Object'
            }
          },
          getSeries: {
            required: false,
            serializedName: 'getSeries',
            type: {
              name: 'Object'
            }
          },
          aggregateSeries: {
            required: false,
            serializedName: 'aggregateSeries',
            type: {
              name: 'Object'
            }
          }
        }
      }
    };
  }
}

module.exports = QueryRequest;
