/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a Restriction.
 */
class Restriction {
  /**
   * Create a Restriction.
   * @property {object} [kind]
   * @property {string} [targetOrganisationId] Target Organisation's Id
   */
  constructor() {
  }

  /**
   * Defines the metadata of Restriction
   *
   * @returns {object} metadata of Restriction
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'Restriction',
      type: {
        name: 'Composite',
        className: 'Restriction',
        modelProperties: {
          kind: {
            required: false,
            serializedName: 'kind',
            type: {
              name: 'Object'
            }
          },
          targetOrganisationId: {
            required: false,
            serializedName: 'targetOrganisationId',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = Restriction;
