/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a Signal.
 */
class Signal {
  /**
   * Create a Signal.
   * @property {string} [id]
   * @property {string} [property]
   * @property {string} [valueType]
   * @property {object} [attributes]
   */
  constructor() {
  }

  /**
   * Defines the metadata of Signal
   *
   * @returns {object} metadata of Signal
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'Signal',
      type: {
        name: 'Composite',
        className: 'Signal',
        modelProperties: {
          id: {
            required: false,
            serializedName: 'id',
            type: {
              name: 'String'
            }
          },
          property: {
            required: false,
            serializedName: 'property',
            type: {
              name: 'String'
            }
          },
          valueType: {
            required: false,
            serializedName: 'valueType',
            type: {
              name: 'String'
            }
          },
          attributes: {
            required: false,
            serializedName: 'attributes',
            type: {
              name: 'Dictionary',
              value: {
                  required: false,
                  serializedName: 'StringElementType',
                  type: {
                    name: 'String'
                  }
              }
            }
          }
        }
      }
    };
  }
}

module.exports = Signal;
