/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a Summary.
 */
class Summary {
  /**
   * Create a Summary.
   * @property {string} [query]
   * @property {string} [queryType]
   * @property {number} [queryTime]
   * @property {number} [numResults]
   * @property {number} [offset]
   * @property {number} [totalResults]
   * @property {number} [fuzzyLevel]
   */
  constructor() {
  }

  /**
   * Defines the metadata of Summary
   *
   * @returns {object} metadata of Summary
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'Summary',
      type: {
        name: 'Composite',
        className: 'Summary',
        modelProperties: {
          query: {
            required: false,
            serializedName: 'query',
            type: {
              name: 'String'
            }
          },
          queryType: {
            required: false,
            serializedName: 'queryType',
            type: {
              name: 'String'
            }
          },
          queryTime: {
            required: false,
            serializedName: 'queryTime',
            type: {
              name: 'Number'
            }
          },
          numResults: {
            required: false,
            serializedName: 'numResults',
            type: {
              name: 'Number'
            }
          },
          offset: {
            required: false,
            serializedName: 'offset',
            type: {
              name: 'Number'
            }
          },
          totalResults: {
            required: false,
            serializedName: 'totalResults',
            type: {
              name: 'Number'
            }
          },
          fuzzyLevel: {
            required: false,
            serializedName: 'fuzzyLevel',
            type: {
              name: 'Number'
            }
          }
        }
      }
    };
  }
}

module.exports = Summary;
