/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a TermsAndConditions.
 */
class TermsAndConditions {
  /**
   * Create a TermsAndConditions.
   * @property {string} id
   * @property {string} name
   * @property {string} contents
   */
  constructor() {
  }

  /**
   * Defines the metadata of TermsAndConditions
   *
   * @returns {object} metadata of TermsAndConditions
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'TermsAndConditions',
      type: {
        name: 'Composite',
        className: 'TermsAndConditions',
        modelProperties: {
          id: {
            required: true,
            serializedName: 'id',
            type: {
              name: 'String'
            }
          },
          name: {
            required: true,
            serializedName: 'name',
            type: {
              name: 'String'
            }
          },
          contents: {
            required: true,
            serializedName: 'contents',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = TermsAndConditions;
