/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a TokenRequest.
 */
class TokenRequest {
  /**
   * Create a TokenRequest.
   * @property {string} username
   * @property {string} password
   */
  constructor() {
  }

  /**
   * Defines the metadata of TokenRequest
   *
   * @returns {object} metadata of TokenRequest
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'TokenRequest',
      type: {
        name: 'Composite',
        className: 'TokenRequest',
        modelProperties: {
          username: {
            required: true,
            serializedName: 'username',
            type: {
              name: 'String'
            }
          },
          password: {
            required: true,
            serializedName: 'password',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = TokenRequest;
