/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a UpdateSignal.
 */
class UpdateSignal {
  /**
   * Create a UpdateSignal.
   * @property {object} [meta]
   */
  constructor() {
  }

  /**
   * Defines the metadata of UpdateSignal
   *
   * @returns {object} metadata of UpdateSignal
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'UpdateSignal',
      type: {
        name: 'Composite',
        className: 'UpdateSignal',
        modelProperties: {
          meta: {
            required: false,
            serializedName: 'meta',
            type: {
              name: 'Dictionary',
              value: {
                  required: false,
                  serializedName: 'StringElementType',
                  type: {
                    name: 'String'
                  }
              }
            }
          }
        }
      }
    };
  }
}

module.exports = UpdateSignal;
