/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a Viewport.
 */
class Viewport {
  /**
   * Create a Viewport.
   * @property {object} [topLeftPoint]
   * @property {object} [btmRightPoint]
   */
  constructor() {
  }

  /**
   * Defines the metadata of Viewport
   *
   * @returns {object} metadata of Viewport
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'Viewport',
      type: {
        name: 'Composite',
        className: 'Viewport',
        modelProperties: {
          topLeftPoint: {
            required: false,
            serializedName: 'topLeftPoint',
            type: {
              name: 'Object'
            }
          },
          btmRightPoint: {
            required: false,
            serializedName: 'btmRightPoint',
            type: {
              name: 'Object'
            }
          }
        }
      }
    };
  }
}

module.exports = Viewport;
