/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

/* jshint latedef:false */
/* jshint forin:false */
/* jshint noempty:false */

'use strict';

exports.Authentication = require('./authentication');
exports.Market = require('./market');
exports.OrganisationRestriction = require('./organisationRestriction');
exports.Organisations = require('./organisations');
exports.Search = require('./search');
exports.Users = require('./users');
exports.Version = require('./version');
exports.AccountOperations = require('./accountOperations');
exports.TermsAndConditionsOperations = require('./termsAndConditionsOperations');
exports.Amphorae = require('./amphorae');
exports.AmphoraeFiles = require('./amphoraeFiles');
exports.AmphoraeSignals = require('./amphoraeSignals');
exports.Purchases = require('./purchases');
exports.TimeSeries = require('./timeSeries');
