/**
 * Amphora Data Api
 * API for interacting with the Amphora Data platform.
 *
 * The version of the OpenAPI document: 0.9.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AccessRuleDtoBase model module.
 * @module model/AccessRuleDtoBase
 * @version 0.9.7
 */
class AccessRuleDtoBase {
    /**
     * Constructs a new <code>AccessRuleDtoBase</code>.
     * @alias module:model/AccessRuleDtoBase
     */
    constructor() { 
        
        AccessRuleDtoBase.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AccessRuleDtoBase</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AccessRuleDtoBase} obj Optional instance to populate.
     * @return {module:model/AccessRuleDtoBase} The populated <code>AccessRuleDtoBase</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AccessRuleDtoBase();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('allowOrDeny')) {
                obj['allowOrDeny'] = ApiClient.convertToType(data['allowOrDeny'], 'String');
            }
            if (data.hasOwnProperty('priority')) {
                obj['priority'] = ApiClient.convertToType(data['priority'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
AccessRuleDtoBase.prototype['id'] = undefined;

/**
 * @member {String} allowOrDeny
 */
AccessRuleDtoBase.prototype['allowOrDeny'] = undefined;

/**
 * @member {Number} priority
 */
AccessRuleDtoBase.prototype['priority'] = undefined;






export default AccessRuleDtoBase;

