/**
 * Amphora Data Api
 * API for interacting with the Amphora Data platform.
 *
 * The version of the OpenAPI document: 0.9.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Address model module.
 * @module model/Address
 * @version 0.9.7
 */
class Address {
    /**
     * Constructs a new <code>Address</code>.
     * @alias module:model/Address
     */
    constructor() { 
        
        Address.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Address</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Address} obj Optional instance to populate.
     * @return {module:model/Address} The populated <code>Address</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Address();

            if (data.hasOwnProperty('streetNumber')) {
                obj['streetNumber'] = ApiClient.convertToType(data['streetNumber'], 'String');
            }
            if (data.hasOwnProperty('streetName')) {
                obj['streetName'] = ApiClient.convertToType(data['streetName'], 'String');
            }
            if (data.hasOwnProperty('municipalitySubdivision')) {
                obj['municipalitySubdivision'] = ApiClient.convertToType(data['municipalitySubdivision'], 'String');
            }
            if (data.hasOwnProperty('municipality')) {
                obj['municipality'] = ApiClient.convertToType(data['municipality'], 'String');
            }
            if (data.hasOwnProperty('countrySecondarySubdivision')) {
                obj['countrySecondarySubdivision'] = ApiClient.convertToType(data['countrySecondarySubdivision'], 'String');
            }
            if (data.hasOwnProperty('countrySubdivision')) {
                obj['countrySubdivision'] = ApiClient.convertToType(data['countrySubdivision'], 'String');
            }
            if (data.hasOwnProperty('postalCode')) {
                obj['postalCode'] = ApiClient.convertToType(data['postalCode'], 'String');
            }
            if (data.hasOwnProperty('countryCode')) {
                obj['countryCode'] = ApiClient.convertToType(data['countryCode'], 'String');
            }
            if (data.hasOwnProperty('country')) {
                obj['country'] = ApiClient.convertToType(data['country'], 'String');
            }
            if (data.hasOwnProperty('countryCodeIso3')) {
                obj['countryCodeIso3'] = ApiClient.convertToType(data['countryCodeIso3'], 'String');
            }
            if (data.hasOwnProperty('freeformAddress')) {
                obj['freeformAddress'] = ApiClient.convertToType(data['freeformAddress'], 'String');
            }
            if (data.hasOwnProperty('localName')) {
                obj['localName'] = ApiClient.convertToType(data['localName'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} streetNumber
 */
Address.prototype['streetNumber'] = undefined;

/**
 * @member {String} streetName
 */
Address.prototype['streetName'] = undefined;

/**
 * @member {String} municipalitySubdivision
 */
Address.prototype['municipalitySubdivision'] = undefined;

/**
 * @member {String} municipality
 */
Address.prototype['municipality'] = undefined;

/**
 * @member {String} countrySecondarySubdivision
 */
Address.prototype['countrySecondarySubdivision'] = undefined;

/**
 * @member {String} countrySubdivision
 */
Address.prototype['countrySubdivision'] = undefined;

/**
 * @member {String} postalCode
 */
Address.prototype['postalCode'] = undefined;

/**
 * @member {String} countryCode
 */
Address.prototype['countryCode'] = undefined;

/**
 * @member {String} country
 */
Address.prototype['country'] = undefined;

/**
 * @member {String} countryCodeIso3
 */
Address.prototype['countryCodeIso3'] = undefined;

/**
 * @member {String} freeformAddress
 */
Address.prototype['freeformAddress'] = undefined;

/**
 * @member {String} localName
 */
Address.prototype['localName'] = undefined;






export default Address;

