/**
 * Amphora Data Api
 * API for interacting with the Amphora Data platform.
 *
 * The version of the OpenAPI document: 0.9.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AmphoraUserAllOf model module.
 * @module model/AmphoraUserAllOf
 * @version 0.9.7
 */
class AmphoraUserAllOf {
    /**
     * Constructs a new <code>AmphoraUserAllOf</code>.
     * @alias module:model/AmphoraUserAllOf
     */
    constructor() { 
        
        AmphoraUserAllOf.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AmphoraUserAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AmphoraUserAllOf} obj Optional instance to populate.
     * @return {module:model/AmphoraUserAllOf} The populated <code>AmphoraUserAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AmphoraUserAllOf();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('organisationId')) {
                obj['organisationId'] = ApiClient.convertToType(data['organisationId'], 'String');
            }
            if (data.hasOwnProperty('lastModified')) {
                obj['lastModified'] = ApiClient.convertToType(data['lastModified'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
AmphoraUserAllOf.prototype['id'] = undefined;

/**
 * @member {String} email
 */
AmphoraUserAllOf.prototype['email'] = undefined;

/**
 * @member {String} organisationId
 */
AmphoraUserAllOf.prototype['organisationId'] = undefined;

/**
 * @member {Date} lastModified
 */
AmphoraUserAllOf.prototype['lastModified'] = undefined;






export default AmphoraUserAllOf;

