/**
 * Amphora Data Api
 * API for interacting with the Amphora Data platform.
 *
 * The version of the OpenAPI document: 0.9.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AttributeStore model module.
 * @module model/AttributeStore
 * @version 0.9.7
 */
class AttributeStore {
    /**
     * Constructs a new <code>AttributeStore</code>.
     * @alias module:model/AttributeStore
     */
    constructor() { 
        
        AttributeStore.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AttributeStore</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AttributeStore} obj Optional instance to populate.
     * @return {module:model/AttributeStore} The populated <code>AttributeStore</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AttributeStore();

            if (data.hasOwnProperty('attributes')) {
                obj['attributes'] = ApiClient.convertToType(data['attributes'], {'String': 'String'});
            }
        }
        return obj;
    }


}

/**
 * @member {Object.<String, String>} attributes
 */
AttributeStore.prototype['attributes'] = undefined;






export default AttributeStore;

