/**
 * Amphora Data Api
 * API for interacting with the Amphora Data platform.
 *
 * The version of the OpenAPI document: 0.9.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BaseAmphoraUser model module.
 * @module model/BaseAmphoraUser
 * @version 0.9.7
 */
class BaseAmphoraUser {
    /**
     * Constructs a new <code>BaseAmphoraUser</code>.
     * @alias module:model/BaseAmphoraUser
     * @param fullName {String} 
     * @param userName {String} 
     */
    constructor(fullName, userName) { 
        
        BaseAmphoraUser.initialize(this, fullName, userName);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, fullName, userName) { 
        obj['fullName'] = fullName;
        obj['userName'] = userName;
    }

    /**
     * Constructs a <code>BaseAmphoraUser</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BaseAmphoraUser} obj Optional instance to populate.
     * @return {module:model/BaseAmphoraUser} The populated <code>BaseAmphoraUser</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BaseAmphoraUser();

            if (data.hasOwnProperty('phoneNumber')) {
                obj['phoneNumber'] = ApiClient.convertToType(data['phoneNumber'], 'String');
            }
            if (data.hasOwnProperty('about')) {
                obj['about'] = ApiClient.convertToType(data['about'], 'String');
            }
            if (data.hasOwnProperty('fullName')) {
                obj['fullName'] = ApiClient.convertToType(data['fullName'], 'String');
            }
            if (data.hasOwnProperty('userName')) {
                obj['userName'] = ApiClient.convertToType(data['userName'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} phoneNumber
 */
BaseAmphoraUser.prototype['phoneNumber'] = undefined;

/**
 * @member {String} about
 */
BaseAmphoraUser.prototype['about'] = undefined;

/**
 * @member {String} fullName
 */
BaseAmphoraUser.prototype['fullName'] = undefined;

/**
 * @member {String} userName
 */
BaseAmphoraUser.prototype['userName'] = undefined;






export default BaseAmphoraUser;

