/**
 * Amphora Data Api
 * API for interacting with the Amphora Data platform.
 *
 * The version of the OpenAPI document: 0.9.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CategorySet model module.
 * @module model/CategorySet
 * @version 0.9.7
 */
class CategorySet {
    /**
     * Constructs a new <code>CategorySet</code>.
     * @alias module:model/CategorySet
     */
    constructor() { 
        
        CategorySet.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CategorySet</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CategorySet} obj Optional instance to populate.
     * @return {module:model/CategorySet} The populated <code>CategorySet</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CategorySet();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
CategorySet.prototype['id'] = undefined;






export default CategorySet;

