/**
 * Amphora Data Api
 * API for interacting with the Amphora Data platform.
 *
 * The version of the OpenAPI document: 0.9.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Name from './Name';

/**
 * The Classification model module.
 * @module model/Classification
 * @version 0.9.7
 */
class Classification {
    /**
     * Constructs a new <code>Classification</code>.
     * @alias module:model/Classification
     */
    constructor() { 
        
        Classification.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Classification</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Classification} obj Optional instance to populate.
     * @return {module:model/Classification} The populated <code>Classification</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Classification();

            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
            if (data.hasOwnProperty('names')) {
                obj['names'] = ApiClient.convertToType(data['names'], [Name]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} code
 */
Classification.prototype['code'] = undefined;

/**
 * @member {Array.<module:model/Name>} names
 */
Classification.prototype['names'] = undefined;






export default Classification;

