/**
 * Amphora Data Api
 * API for interacting with the Amphora Data platform.
 *
 * The version of the OpenAPI document: 0.9.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AttributeStore from './AttributeStore';
import DetailedAmphoraAllOf from './DetailedAmphoraAllOf';
import EditAmphora from './EditAmphora';

/**
 * The DetailedAmphora model module.
 * @module model/DetailedAmphora
 * @version 0.9.7
 */
class DetailedAmphora {
    /**
     * Constructs a new <code>DetailedAmphora</code>.
     * @alias module:model/DetailedAmphora
     * @implements module:model/EditAmphora
     * @implements module:model/DetailedAmphoraAllOf
     * @param name {String} 
     * @param price {Number} 
     * @param description {String} 
     */
    constructor(name, price, description) { 
        EditAmphora.initialize(this, name, price, description);DetailedAmphoraAllOf.initialize(this);
        DetailedAmphora.initialize(this, name, price, description);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, price, description) { 
        obj['name'] = name;
        obj['price'] = price;
        obj['description'] = description;
    }

    /**
     * Constructs a <code>DetailedAmphora</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DetailedAmphora} obj Optional instance to populate.
     * @return {module:model/DetailedAmphora} The populated <code>DetailedAmphora</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DetailedAmphora();
            EditAmphora.constructFromObject(data, obj);
            DetailedAmphoraAllOf.constructFromObject(data, obj);

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('isDeleted')) {
                obj['isDeleted'] = ApiClient.convertToType(data['isDeleted'], 'Boolean');
            }
            if (data.hasOwnProperty('createdDate')) {
                obj['createdDate'] = ApiClient.convertToType(data['createdDate'], 'Date');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('price')) {
                obj['price'] = ApiClient.convertToType(data['price'], 'Number');
            }
            if (data.hasOwnProperty('labels')) {
                obj['labels'] = ApiClient.convertToType(data['labels'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('lat')) {
                obj['lat'] = ApiClient.convertToType(data['lat'], 'Number');
            }
            if (data.hasOwnProperty('lon')) {
                obj['lon'] = ApiClient.convertToType(data['lon'], 'Number');
            }
            if (data.hasOwnProperty('termsAndConditionsId')) {
                obj['termsAndConditionsId'] = ApiClient.convertToType(data['termsAndConditionsId'], 'String');
            }
            if (data.hasOwnProperty('fileAttributes')) {
                obj['fileAttributes'] = ApiClient.convertToType(data['fileAttributes'], {'String': AttributeStore});
            }
            if (data.hasOwnProperty('organisationId')) {
                obj['organisationId'] = ApiClient.convertToType(data['organisationId'], 'String');
            }
            if (data.hasOwnProperty('purchaseCount')) {
                obj['purchaseCount'] = ApiClient.convertToType(data['purchaseCount'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
DetailedAmphora.prototype['id'] = undefined;

/**
 * @member {Boolean} isDeleted
 */
DetailedAmphora.prototype['isDeleted'] = undefined;

/**
 * @member {Date} createdDate
 */
DetailedAmphora.prototype['createdDate'] = undefined;

/**
 * @member {String} name
 */
DetailedAmphora.prototype['name'] = undefined;

/**
 * @member {Number} price
 */
DetailedAmphora.prototype['price'] = undefined;

/**
 * @member {String} labels
 */
DetailedAmphora.prototype['labels'] = undefined;

/**
 * @member {String} description
 */
DetailedAmphora.prototype['description'] = undefined;

/**
 * @member {Number} lat
 */
DetailedAmphora.prototype['lat'] = undefined;

/**
 * @member {Number} lon
 */
DetailedAmphora.prototype['lon'] = undefined;

/**
 * @member {String} termsAndConditionsId
 */
DetailedAmphora.prototype['termsAndConditionsId'] = undefined;

/**
 * @member {Object.<String, module:model/AttributeStore>} fileAttributes
 */
DetailedAmphora.prototype['fileAttributes'] = undefined;

/**
 * @member {String} organisationId
 */
DetailedAmphora.prototype['organisationId'] = undefined;

/**
 * @member {Number} purchaseCount
 */
DetailedAmphora.prototype['purchaseCount'] = undefined;


// Implement EditAmphora interface:
/**
 * @member {String} id
 */
EditAmphora.prototype['id'] = undefined;
/**
 * @member {Boolean} isDeleted
 */
EditAmphora.prototype['isDeleted'] = undefined;
/**
 * @member {Date} createdDate
 */
EditAmphora.prototype['createdDate'] = undefined;
/**
 * @member {String} name
 */
EditAmphora.prototype['name'] = undefined;
/**
 * @member {Number} price
 */
EditAmphora.prototype['price'] = undefined;
/**
 * @member {String} labels
 */
EditAmphora.prototype['labels'] = undefined;
/**
 * @member {String} description
 */
EditAmphora.prototype['description'] = undefined;
/**
 * @member {Number} lat
 */
EditAmphora.prototype['lat'] = undefined;
/**
 * @member {Number} lon
 */
EditAmphora.prototype['lon'] = undefined;
/**
 * @member {String} termsAndConditionsId
 */
EditAmphora.prototype['termsAndConditionsId'] = undefined;
/**
 * @member {Object.<String, module:model/AttributeStore>} fileAttributes
 */
EditAmphora.prototype['fileAttributes'] = undefined;
// Implement DetailedAmphoraAllOf interface:
/**
 * @member {String} organisationId
 */
DetailedAmphoraAllOf.prototype['organisationId'] = undefined;
/**
 * @member {Number} purchaseCount
 */
DetailedAmphoraAllOf.prototype['purchaseCount'] = undefined;




export default DetailedAmphora;

