/**
 * Amphora Data Api
 * API for interacting with the Amphora Data platform.
 *
 * The version of the OpenAPI document: 0.9.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import OneOfSummary from './OneOfSummary';
import Result from './Result';

/**
 * The FuzzySearchResponse model module.
 * @module model/FuzzySearchResponse
 * @version 0.9.7
 */
class FuzzySearchResponse {
    /**
     * Constructs a new <code>FuzzySearchResponse</code>.
     * @alias module:model/FuzzySearchResponse
     */
    constructor() { 
        
        FuzzySearchResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>FuzzySearchResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FuzzySearchResponse} obj Optional instance to populate.
     * @return {module:model/FuzzySearchResponse} The populated <code>FuzzySearchResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FuzzySearchResponse();

            if (data.hasOwnProperty('summary')) {
                obj['summary'] = ApiClient.convertToType(data['summary'], OneOfSummary);
            }
            if (data.hasOwnProperty('results')) {
                obj['results'] = ApiClient.convertToType(data['results'], [Result]);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/OneOfSummary} summary
 */
FuzzySearchResponse.prototype['summary'] = undefined;

/**
 * @member {Array.<module:model/Result>} results
 */
FuzzySearchResponse.prototype['results'] = undefined;






export default FuzzySearchResponse;

