/**
 * Amphora Data Api
 * API for interacting with the Amphora Data platform.
 *
 * The version of the OpenAPI document: 0.9.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import OneOfDateTimeRange from './OneOfDateTimeRange';
import OneOfTsx from './OneOfTsx';
import Variable from './Variable';

/**
 * The GetSeries model module.
 * @module model/GetSeries
 * @version 0.9.7
 */
class GetSeries {
    /**
     * Constructs a new <code>GetSeries</code>.
     * @alias module:model/GetSeries
     */
    constructor() { 
        
        GetSeries.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetSeries</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetSeries} obj Optional instance to populate.
     * @return {module:model/GetSeries} The populated <code>GetSeries</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetSeries();

            if (data.hasOwnProperty('timeSeriesId')) {
                obj['timeSeriesId'] = ApiClient.convertToType(data['timeSeriesId'], [Object]);
            }
            if (data.hasOwnProperty('searchSpan')) {
                obj['searchSpan'] = ApiClient.convertToType(data['searchSpan'], OneOfDateTimeRange);
            }
            if (data.hasOwnProperty('filter')) {
                obj['filter'] = ApiClient.convertToType(data['filter'], OneOfTsx);
            }
            if (data.hasOwnProperty('projectedVariables')) {
                obj['projectedVariables'] = ApiClient.convertToType(data['projectedVariables'], ['String']);
            }
            if (data.hasOwnProperty('inlineVariables')) {
                obj['inlineVariables'] = ApiClient.convertToType(data['inlineVariables'], {'String': Variable});
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<Object>} timeSeriesId
 */
GetSeries.prototype['timeSeriesId'] = undefined;

/**
 * @member {module:model/OneOfDateTimeRange} searchSpan
 */
GetSeries.prototype['searchSpan'] = undefined;

/**
 * @member {module:model/OneOfTsx} filter
 */
GetSeries.prototype['filter'] = undefined;

/**
 * @member {Array.<String>} projectedVariables
 */
GetSeries.prototype['projectedVariables'] = undefined;

/**
 * @member {Object.<String, module:model/Variable>} inlineVariables
 */
GetSeries.prototype['inlineVariables'] = undefined;






export default GetSeries;

