/**
 * Amphora Data Api
 * API for interacting with the Amphora Data platform.
 *
 * The version of the OpenAPI document: 0.9.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Name model module.
 * @module model/Name
 * @version 0.9.7
 */
class Name {
    /**
     * Constructs a new <code>Name</code>.
     * @alias module:model/Name
     */
    constructor() { 
        
        Name.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Name</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Name} obj Optional instance to populate.
     * @return {module:model/Name} The populated <code>Name</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Name();

            if (data.hasOwnProperty('nameLocale')) {
                obj['nameLocale'] = ApiClient.convertToType(data['nameLocale'], 'String');
            }
            if (data.hasOwnProperty('nameName')) {
                obj['nameName'] = ApiClient.convertToType(data['nameName'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} nameLocale
 */
Name.prototype['nameLocale'] = undefined;

/**
 * @member {String} nameName
 */
Name.prototype['nameName'] = undefined;






export default Name;

