/**
 * Amphora Data Api
 * API for interacting with the Amphora Data platform.
 *
 * The version of the OpenAPI document: 0.9.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import OneOfTsx from './OneOfTsx';

/**
 * The NumericVariable model module.
 * @module model/NumericVariable
 * @version 0.9.7
 */
class NumericVariable {
    /**
     * Constructs a new <code>NumericVariable</code>.
     * @alias module:model/NumericVariable
     * @param kind {String} 
     */
    constructor(kind) { 
        
        NumericVariable.initialize(this, kind);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, kind) { 
        obj['kind'] = kind;
    }

    /**
     * Constructs a <code>NumericVariable</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/NumericVariable} obj Optional instance to populate.
     * @return {module:model/NumericVariable} The populated <code>NumericVariable</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NumericVariable();

            if (data.hasOwnProperty('filter')) {
                obj['filter'] = ApiClient.convertToType(data['filter'], OneOfTsx);
            }
            if (data.hasOwnProperty('kind')) {
                obj['kind'] = ApiClient.convertToType(data['kind'], 'String');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], OneOfTsx);
            }
            if (data.hasOwnProperty('aggregation')) {
                obj['aggregation'] = ApiClient.convertToType(data['aggregation'], OneOfTsx);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/OneOfTsx} filter
 */
NumericVariable.prototype['filter'] = undefined;

/**
 * @member {String} kind
 */
NumericVariable.prototype['kind'] = undefined;

/**
 * @member {module:model/OneOfTsx} value
 */
NumericVariable.prototype['value'] = undefined;

/**
 * @member {module:model/OneOfTsx} aggregation
 */
NumericVariable.prototype['aggregation'] = undefined;






export default NumericVariable;

