/**
 * Amphora Data Api
 * API for interacting with the Amphora Data platform.
 *
 * The version of the OpenAPI document: 0.9.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The OrganisationAllOf model module.
 * @module model/OrganisationAllOf
 * @version 0.9.7
 */
class OrganisationAllOf {
    /**
     * Constructs a new <code>OrganisationAllOf</code>.
     * @alias module:model/OrganisationAllOf
     * @param name {String} 
     * @param about {String} 
     * @param websiteUrl {String} 
     */
    constructor(name, about, websiteUrl) { 
        
        OrganisationAllOf.initialize(this, name, about, websiteUrl);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, about, websiteUrl) { 
        obj['name'] = name;
        obj['about'] = about;
        obj['websiteUrl'] = websiteUrl;
    }

    /**
     * Constructs a <code>OrganisationAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OrganisationAllOf} obj Optional instance to populate.
     * @return {module:model/OrganisationAllOf} The populated <code>OrganisationAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OrganisationAllOf();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('about')) {
                obj['about'] = ApiClient.convertToType(data['about'], 'String');
            }
            if (data.hasOwnProperty('websiteUrl')) {
                obj['websiteUrl'] = ApiClient.convertToType(data['websiteUrl'], 'String');
            }
            if (data.hasOwnProperty('address')) {
                obj['address'] = ApiClient.convertToType(data['address'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
OrganisationAllOf.prototype['name'] = undefined;

/**
 * @member {String} about
 */
OrganisationAllOf.prototype['about'] = undefined;

/**
 * @member {String} websiteUrl
 */
OrganisationAllOf.prototype['websiteUrl'] = undefined;

/**
 * @member {String} address
 */
OrganisationAllOf.prototype['address'] = undefined;






export default OrganisationAllOf;

