/**
 * Amphora Data Api
 * API for interacting with the Amphora Data platform.
 *
 * The version of the OpenAPI document: 0.9.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The OrganisationAccessRuleAllOf model module.
 * @module model/OrganisationAccessRuleAllOf
 * @version 0.9.7
 */
class OrganisationAccessRuleAllOf {
    /**
     * Constructs a new <code>OrganisationAccessRuleAllOf</code>.
     * @alias module:model/OrganisationAccessRuleAllOf
     * @param organisationId {String} 
     */
    constructor(organisationId) { 
        
        OrganisationAccessRuleAllOf.initialize(this, organisationId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, organisationId) { 
        obj['organisationId'] = organisationId;
    }

    /**
     * Constructs a <code>OrganisationAccessRuleAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OrganisationAccessRuleAllOf} obj Optional instance to populate.
     * @return {module:model/OrganisationAccessRuleAllOf} The populated <code>OrganisationAccessRuleAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OrganisationAccessRuleAllOf();

            if (data.hasOwnProperty('organisationId')) {
                obj['organisationId'] = ApiClient.convertToType(data['organisationId'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} organisationId
 */
OrganisationAccessRuleAllOf.prototype['organisationId'] = undefined;






export default OrganisationAccessRuleAllOf;

