/**
 * Amphora Data Api
 * API for interacting with the Amphora Data platform.
 *
 * The version of the OpenAPI document: 0.9.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PagedResponse model module.
 * @module model/PagedResponse
 * @version 0.9.7
 */
class PagedResponse {
    /**
     * Constructs a new <code>PagedResponse</code>.
     * @alias module:model/PagedResponse
     */
    constructor() { 
        
        PagedResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PagedResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PagedResponse} obj Optional instance to populate.
     * @return {module:model/PagedResponse} The populated <code>PagedResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PagedResponse();

            if (data.hasOwnProperty('continuationToken')) {
                obj['continuationToken'] = ApiClient.convertToType(data['continuationToken'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} continuationToken
 */
PagedResponse.prototype['continuationToken'] = undefined;






export default PagedResponse;

