/**
 * Amphora Data Api
 * API for interacting with the Amphora Data platform.
 *
 * The version of the OpenAPI document: 0.9.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PropertyValuesAllOf model module.
 * @module model/PropertyValuesAllOf
 * @version 0.9.7
 */
class PropertyValuesAllOf {
    /**
     * Constructs a new <code>PropertyValuesAllOf</code>.
     * @alias module:model/PropertyValuesAllOf
     */
    constructor() { 
        
        PropertyValuesAllOf.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PropertyValuesAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PropertyValuesAllOf} obj Optional instance to populate.
     * @return {module:model/PropertyValuesAllOf} The populated <code>PropertyValuesAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PropertyValuesAllOf();

            if (data.hasOwnProperty('values')) {
                obj['values'] = ApiClient.convertToType(data['values'], [Object]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<Object>} values
 */
PropertyValuesAllOf.prototype['values'] = undefined;






export default PropertyValuesAllOf;

