/**
 * Amphora Data Api
 * API for interacting with the Amphora Data platform.
 *
 * The version of the OpenAPI document: 0.9.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PagedResponse from './PagedResponse';
import PropertyValues from './PropertyValues';
import QueryResultPageAllOf from './QueryResultPageAllOf';

/**
 * The QueryResultPage model module.
 * @module model/QueryResultPage
 * @version 0.9.7
 */
class QueryResultPage {
    /**
     * Constructs a new <code>QueryResultPage</code>.
     * @alias module:model/QueryResultPage
     * @implements module:model/PagedResponse
     * @implements module:model/QueryResultPageAllOf
     */
    constructor() { 
        PagedResponse.initialize(this);QueryResultPageAllOf.initialize(this);
        QueryResultPage.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>QueryResultPage</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/QueryResultPage} obj Optional instance to populate.
     * @return {module:model/QueryResultPage} The populated <code>QueryResultPage</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new QueryResultPage();
            PagedResponse.constructFromObject(data, obj);
            QueryResultPageAllOf.constructFromObject(data, obj);

            if (data.hasOwnProperty('continuationToken')) {
                obj['continuationToken'] = ApiClient.convertToType(data['continuationToken'], 'String');
            }
            if (data.hasOwnProperty('timestamps')) {
                obj['timestamps'] = ApiClient.convertToType(data['timestamps'], ['Date']);
            }
            if (data.hasOwnProperty('properties')) {
                obj['properties'] = ApiClient.convertToType(data['properties'], [PropertyValues]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} continuationToken
 */
QueryResultPage.prototype['continuationToken'] = undefined;

/**
 * @member {Array.<Date>} timestamps
 */
QueryResultPage.prototype['timestamps'] = undefined;

/**
 * @member {Array.<module:model/PropertyValues>} properties
 */
QueryResultPage.prototype['properties'] = undefined;


// Implement PagedResponse interface:
/**
 * @member {String} continuationToken
 */
PagedResponse.prototype['continuationToken'] = undefined;
// Implement QueryResultPageAllOf interface:
/**
 * @member {Array.<Date>} timestamps
 */
QueryResultPageAllOf.prototype['timestamps'] = undefined;
/**
 * @member {Array.<module:model/PropertyValues>} properties
 */
QueryResultPageAllOf.prototype['properties'] = undefined;




export default QueryResultPage;

