/**
 * Amphora Data Api
 * API for interacting with the Amphora Data platform.
 *
 * The version of the OpenAPI document: 0.9.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import OneOfAggregateSeries from './OneOfAggregateSeries';
import OneOfGetEvents from './OneOfGetEvents';
import OneOfGetSeries from './OneOfGetSeries';

/**
 * The QueryRequest model module.
 * @module model/QueryRequest
 * @version 0.9.7
 */
class QueryRequest {
    /**
     * Constructs a new <code>QueryRequest</code>.
     * @alias module:model/QueryRequest
     */
    constructor() { 
        
        QueryRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>QueryRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/QueryRequest} obj Optional instance to populate.
     * @return {module:model/QueryRequest} The populated <code>QueryRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new QueryRequest();

            if (data.hasOwnProperty('getEvents')) {
                obj['getEvents'] = ApiClient.convertToType(data['getEvents'], OneOfGetEvents);
            }
            if (data.hasOwnProperty('getSeries')) {
                obj['getSeries'] = ApiClient.convertToType(data['getSeries'], OneOfGetSeries);
            }
            if (data.hasOwnProperty('aggregateSeries')) {
                obj['aggregateSeries'] = ApiClient.convertToType(data['aggregateSeries'], OneOfAggregateSeries);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/OneOfGetEvents} getEvents
 */
QueryRequest.prototype['getEvents'] = undefined;

/**
 * @member {module:model/OneOfGetSeries} getSeries
 */
QueryRequest.prototype['getSeries'] = undefined;

/**
 * @member {module:model/OneOfAggregateSeries} aggregateSeries
 */
QueryRequest.prototype['aggregateSeries'] = undefined;






export default QueryRequest;

