/**
 * Amphora Data Api
 * API for interacting with the Amphora Data platform.
 *
 * The version of the OpenAPI document: 0.9.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PropertyValues from './PropertyValues';

/**
 * The QueryResultPageAllOf model module.
 * @module model/QueryResultPageAllOf
 * @version 0.9.7
 */
class QueryResultPageAllOf {
    /**
     * Constructs a new <code>QueryResultPageAllOf</code>.
     * @alias module:model/QueryResultPageAllOf
     */
    constructor() { 
        
        QueryResultPageAllOf.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>QueryResultPageAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/QueryResultPageAllOf} obj Optional instance to populate.
     * @return {module:model/QueryResultPageAllOf} The populated <code>QueryResultPageAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new QueryResultPageAllOf();

            if (data.hasOwnProperty('timestamps')) {
                obj['timestamps'] = ApiClient.convertToType(data['timestamps'], ['Date']);
            }
            if (data.hasOwnProperty('properties')) {
                obj['properties'] = ApiClient.convertToType(data['properties'], [PropertyValues]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<Date>} timestamps
 */
QueryResultPageAllOf.prototype['timestamps'] = undefined;

/**
 * @member {Array.<module:model/PropertyValues>} properties
 */
QueryResultPageAllOf.prototype['properties'] = undefined;






export default QueryResultPageAllOf;

