/**
 * Amphora Data Api
 * API for interacting with the Amphora Data platform.
 *
 * The version of the OpenAPI document: 0.9.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SearchParameters2 from './SearchParameters2';

/**
 * The SearchParameters model module.
 * @module model/SearchParameters
 * @version 0.9.7
 */
class SearchParameters {
    /**
     * Constructs a new <code>SearchParameters</code>.
     * @alias module:model/SearchParameters
     * @extends 
     * @implements module:model/SearchParameters2
     */
    constructor() { 
        
        SearchParameters.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SearchParameters</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SearchParameters} obj Optional instance to populate.
     * @return {module:model/SearchParameters} The populated <code>SearchParameters</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SearchParameters();

            ApiClient.constructFromObject(data, obj, '');
            
            SearchParameters2.constructFromObject(data, obj);

        }
        return obj;
    }


}






export default SearchParameters;

