/**
 * Amphora Data Api
 * API for interacting with the Amphora Data platform.
 *
 * The version of the OpenAPI document: 0.9.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Signal model module.
 * @module model/Signal
 * @version 0.9.7
 */
class Signal {
    /**
     * Constructs a new <code>Signal</code>.
     * @alias module:model/Signal
     */
    constructor() { 
        
        Signal.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Signal</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Signal} obj Optional instance to populate.
     * @return {module:model/Signal} The populated <code>Signal</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Signal();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('property')) {
                obj['property'] = ApiClient.convertToType(data['property'], 'String');
            }
            if (data.hasOwnProperty('valueType')) {
                obj['valueType'] = ApiClient.convertToType(data['valueType'], 'String');
            }
            if (data.hasOwnProperty('attributes')) {
                obj['attributes'] = ApiClient.convertToType(data['attributes'], {'String': 'String'});
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
Signal.prototype['id'] = undefined;

/**
 * @member {String} property
 */
Signal.prototype['property'] = undefined;

/**
 * @member {String} valueType
 */
Signal.prototype['valueType'] = undefined;

/**
 * @member {Object.<String, String>} attributes
 */
Signal.prototype['attributes'] = undefined;






export default Signal;

