/**
 * Amphora Data Api
 * API for interacting with the Amphora Data platform.
 *
 * The version of the OpenAPI document: 0.9.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Summary model module.
 * @module model/Summary
 * @version 0.9.7
 */
class Summary {
    /**
     * Constructs a new <code>Summary</code>.
     * @alias module:model/Summary
     */
    constructor() { 
        
        Summary.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Summary</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Summary} obj Optional instance to populate.
     * @return {module:model/Summary} The populated <code>Summary</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Summary();

            if (data.hasOwnProperty('query')) {
                obj['query'] = ApiClient.convertToType(data['query'], 'String');
            }
            if (data.hasOwnProperty('queryType')) {
                obj['queryType'] = ApiClient.convertToType(data['queryType'], 'String');
            }
            if (data.hasOwnProperty('queryTime')) {
                obj['queryTime'] = ApiClient.convertToType(data['queryTime'], 'Number');
            }
            if (data.hasOwnProperty('numResults')) {
                obj['numResults'] = ApiClient.convertToType(data['numResults'], 'Number');
            }
            if (data.hasOwnProperty('offset')) {
                obj['offset'] = ApiClient.convertToType(data['offset'], 'Number');
            }
            if (data.hasOwnProperty('totalResults')) {
                obj['totalResults'] = ApiClient.convertToType(data['totalResults'], 'Number');
            }
            if (data.hasOwnProperty('fuzzyLevel')) {
                obj['fuzzyLevel'] = ApiClient.convertToType(data['fuzzyLevel'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} query
 */
Summary.prototype['query'] = undefined;

/**
 * @member {String} queryType
 */
Summary.prototype['queryType'] = undefined;

/**
 * @member {Number} queryTime
 */
Summary.prototype['queryTime'] = undefined;

/**
 * @member {Number} numResults
 */
Summary.prototype['numResults'] = undefined;

/**
 * @member {Number} offset
 */
Summary.prototype['offset'] = undefined;

/**
 * @member {Number} totalResults
 */
Summary.prototype['totalResults'] = undefined;

/**
 * @member {Number} fuzzyLevel
 */
Summary.prototype['fuzzyLevel'] = undefined;






export default Summary;

