/**
 * Amphora Data Api
 * API for interacting with the Amphora Data platform.
 *
 * The version of the OpenAPI document: 0.9.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Tsx model module.
 * @module model/Tsx
 * @version 0.9.7
 */
class Tsx {
    /**
     * Constructs a new <code>Tsx</code>.
     * @alias module:model/Tsx
     */
    constructor() { 
        
        Tsx.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Tsx</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Tsx} obj Optional instance to populate.
     * @return {module:model/Tsx} The populated <code>Tsx</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Tsx();

            if (data.hasOwnProperty('tsx')) {
                obj['tsx'] = ApiClient.convertToType(data['tsx'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} tsx
 */
Tsx.prototype['tsx'] = undefined;






export default Tsx;

