/**
 * Amphora Data Api
 * API for interacting with the Amphora Data platform.
 *
 * The version of the OpenAPI document: 0.9.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AccessRuleDtoBase from './AccessRuleDtoBase';
import UserAccessRuleAllOf from './UserAccessRuleAllOf';

/**
 * The UserAccessRule model module.
 * @module model/UserAccessRule
 * @version 0.9.7
 */
class UserAccessRule {
    /**
     * Constructs a new <code>UserAccessRule</code>.
     * @alias module:model/UserAccessRule
     * @implements module:model/AccessRuleDtoBase
     * @implements module:model/UserAccessRuleAllOf
     * @param username {String} 
     */
    constructor(username) { 
        AccessRuleDtoBase.initialize(this);UserAccessRuleAllOf.initialize(this, username);
        UserAccessRule.initialize(this, username);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, username) { 
        obj['username'] = username;
    }

    /**
     * Constructs a <code>UserAccessRule</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserAccessRule} obj Optional instance to populate.
     * @return {module:model/UserAccessRule} The populated <code>UserAccessRule</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserAccessRule();
            AccessRuleDtoBase.constructFromObject(data, obj);
            UserAccessRuleAllOf.constructFromObject(data, obj);

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('allowOrDeny')) {
                obj['allowOrDeny'] = ApiClient.convertToType(data['allowOrDeny'], 'String');
            }
            if (data.hasOwnProperty('priority')) {
                obj['priority'] = ApiClient.convertToType(data['priority'], 'Number');
            }
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
UserAccessRule.prototype['id'] = undefined;

/**
 * @member {String} allowOrDeny
 */
UserAccessRule.prototype['allowOrDeny'] = undefined;

/**
 * @member {Number} priority
 */
UserAccessRule.prototype['priority'] = undefined;

/**
 * @member {String} username
 */
UserAccessRule.prototype['username'] = undefined;


// Implement AccessRuleDtoBase interface:
/**
 * @member {String} id
 */
AccessRuleDtoBase.prototype['id'] = undefined;
/**
 * @member {String} allowOrDeny
 */
AccessRuleDtoBase.prototype['allowOrDeny'] = undefined;
/**
 * @member {Number} priority
 */
AccessRuleDtoBase.prototype['priority'] = undefined;
// Implement UserAccessRuleAllOf interface:
/**
 * @member {String} username
 */
UserAccessRuleAllOf.prototype['username'] = undefined;




export default UserAccessRule;

