/**
 * Amphora Data Api
 * API for interacting with the Amphora Data platform.
 *
 * The version of the OpenAPI document: 0.9.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UserAccessRuleAllOf model module.
 * @module model/UserAccessRuleAllOf
 * @version 0.9.7
 */
class UserAccessRuleAllOf {
    /**
     * Constructs a new <code>UserAccessRuleAllOf</code>.
     * @alias module:model/UserAccessRuleAllOf
     * @param username {String} 
     */
    constructor(username) { 
        
        UserAccessRuleAllOf.initialize(this, username);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, username) { 
        obj['username'] = username;
    }

    /**
     * Constructs a <code>UserAccessRuleAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserAccessRuleAllOf} obj Optional instance to populate.
     * @return {module:model/UserAccessRuleAllOf} The populated <code>UserAccessRuleAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserAccessRuleAllOf();

            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} username
 */
UserAccessRuleAllOf.prototype['username'] = undefined;






export default UserAccessRuleAllOf;

