/**
 * Amphora Data Api
 * API for interacting with the Amphora Data platform.
 *
 * The version of the OpenAPI document: 0.9.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import OneOfPosition from './OneOfPosition';

/**
 * The Viewport model module.
 * @module model/Viewport
 * @version 0.9.7
 */
class Viewport {
    /**
     * Constructs a new <code>Viewport</code>.
     * @alias module:model/Viewport
     */
    constructor() { 
        
        Viewport.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Viewport</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Viewport} obj Optional instance to populate.
     * @return {module:model/Viewport} The populated <code>Viewport</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Viewport();

            if (data.hasOwnProperty('topLeftPoint')) {
                obj['topLeftPoint'] = ApiClient.convertToType(data['topLeftPoint'], OneOfPosition);
            }
            if (data.hasOwnProperty('btmRightPoint')) {
                obj['btmRightPoint'] = ApiClient.convertToType(data['btmRightPoint'], OneOfPosition);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/OneOfPosition} topLeftPoint
 */
Viewport.prototype['topLeftPoint'] = undefined;

/**
 * @member {module:model/OneOfPosition} btmRightPoint
 */
Viewport.prototype['btmRightPoint'] = undefined;






export default Viewport;

